### PR TITLE
Jenkins job builder naginator

### PR DESCRIPTION
**Pull request by mattclegg**
Hey there's a new PR!

@freeletics/operations

### CODE REVIEW

**Comment by BigYopy** [comment]
TBH I don't think will be the best approach, failed job should be fixed not restarted till it succeeds?

**Comment by mattclegg** [comment]
Yeah it should be fixed but while we have some timeout or other random issues it would be nice to at least have the option to restart a failed job automatically.

**Comment by mattclegg** [comment]
We can also set a limit to only restart once. I also don't think it's a good idea that it should restart until it succeeds.

**Comment by mattclegg** [comment]
@hingstarne Thoughts?

**Review by BigYopy — DISMISSED** [review]

**Review by BigYopy — COMMENTED** [review]
https://github.com/openstack-infra/jenkins-job-builder/blob/324e0197c4deb2a515351ae48fbc9cfa58920117/jenkins_jobs/modules/publishers.py#L5983

**Comment by hingstarne** [comment]
From my perspective if we would have stages we could repeat small part of the job like pulling an image or similiar. But not all parts of the job.
I would say repeating it blindly is dangerous

**Comment by mattclegg** [comment]
Yeah, I think we would still need to decide on which jobs would be safe to repeat if failed once. This PR is just for adding the functionality.

**Comment by hingstarne** [comment]
As Ayoub mentioned its already in their branch?

**Comment by mattclegg** [comment]
It's in their branch but as we have our own fork we can't use it...

**Pull request closed without merging**
